module Rails
  module Credentials
    module Conflict
      class EncryptionService
        CIPHER: String

        @key_path: (String | Pathname)
        @env_key: String
        @encryptor: ActiveSupport::MessageEncryptor?

        def initialize: ((String | Pathname) key_path, ?env_key: String) -> void

        def decrypt: (String? encrypted_content) -> String

        def encrypt: (String content) -> String

        def save_encrypted: (String content, (String | Pathname) destination_path) -> Integer

        private

        def encryptor: () -> ActiveSupport::MessageEncryptor

        def read_key: () -> String

        def key_from_env: () -> String?

        def key_from_file: () -> String?
      end
    end
  end
end
