module Rails
  module Credentials
    module Conflict
      class PathResolver
        attr_reader environment: String?

        @environment: String?

        def initialize: (?String? environment) -> void

        def credentials_path: () -> Pathname

        def key_path: () -> Pathname

        def relative_credentials_path: () -> Pathname
      end
    end
  end
end
